FROM arm32v6/golang:1.10-alpine
MAINTAINER Fabian Stäber, fabian@fstab.de

# Edit the LAST_UPDATE variable to force re-run of 'apk update' when building
# the Docker image
ENV LAST_UPDATE=2018-10-07

RUN apk update && apk upgrade

WORKDIR /root

#------------------------------------------------------------------------------
# Basic tools
#------------------------------------------------------------------------------

RUN apk add \
    autoconf \
    bash \
    binutils \
    curl \
    gcc \
    g++ \
    make

#------------------------------------------------------------------------------
# Go development
#------------------------------------------------------------------------------

# golang 1.10.4 is already installed in the base image,
# but we need to set GOPATH because our release script assumes
# GOPATH is /root/go while the base image uses /go.

RUN mkdir -p /root/go/bin /root/go/pkg
ENV GOPATH="/root/go"
ENV PATH="${GOPATH}/bin:${PATH}"

#------------------------------------------------------------------------------
# Create a statically linked Oniguruma library for Linux arm32
#------------------------------------------------------------------------------

# This will create /usr/local/lib/libonig.a

RUN cd /tmp && \
    curl -sLO https://github.com/kkos/oniguruma/releases/download/v5.9.6/onig-5.9.6.tar.gz && \
    tar xfz onig-5.9.6.tar.gz && \
    rm onig-5.9.6.tar.gz && \
    cd /tmp/onig-5.9.6 && \
    ./configure && \
    make && \
    make install && \
    cd /root && \
    rm -r /tmp/onig-5.9.6

#------------------------------------------------------------------------------
# Create compile scripts
#------------------------------------------------------------------------------

COPY check-if-gopath-available.sh compile-linux.sh /root/

RUN ln -s /go /root/go

CMD /root/check-if-gopath-available.sh && echo "Type 'ls' to see the available compile scripts." && exec /bin/bash

