FROM arm64v8/ubuntu:18.04
MAINTAINER Fabian Stäber, fabian@fstab.de

# Edit the LAST_UPDATE variable to force re-run of 'apt-get update' when building
# the Docker image
ENV LAST_UPDATE=2020-02-14

RUN sleep 1 && apt-get update && apt-get upgrade -y

#------------------------------------------------------------------------------
# Basic tools
#------------------------------------------------------------------------------

RUN apt-get install -y \
    autoconf \
    build-essential \
    curl \
    git \
    wget \
    vim

#------------------------------------------------------------------------------
# Go development
#------------------------------------------------------------------------------

# Install golang manually, so we get the latest version.

RUN cd /usr/local && \
    curl --fail -sLO https://dl.google.com/go/go1.13.8.linux-arm64.tar.gz && \
    tar xfz go1.13.8.linux-arm64.tar.gz && \
    rm go1.13.8.linux-arm64.tar.gz && \
    cd / && \
    mkdir -p go/bin go/pkg

ENV GOROOT="/usr/local/go" \
    GOPATH="/go" \
    GOCACHE=/tmp/.cache
ENV PATH="${GOROOT}/bin:${PATH}"
ENV PATH="${GOPATH}/bin:${PATH}"

#------------------------------------------------------------------------------
# Create a statically linked Oniguruma library for Linux arm64
#------------------------------------------------------------------------------

# This will create /usr/local/lib/libonig.a

RUN cd /tmp && \
    curl -sLO https://github.com/kkos/oniguruma/releases/download/v6.9.4/onig-6.9.4.tar.gz && \
    tar xfz onig-6.9.4.tar.gz && \
    rm onig-6.9.4.tar.gz && \
    cd /tmp/onig-6.9.4 && \
    cp /usr/share/misc/config.guess . && \
    ./configure && \
    make && \
    make install && \
    cd / && \
    rm -r /tmp/onig-6.9.4

#------------------------------------------------------------------------------
# Create compile scripts
#------------------------------------------------------------------------------

COPY check-if-gopath-available.sh compile-linux.sh /

CMD /check-if-gopath-available.sh && echo "Type 'ls' to see the available compile scripts." && exec /bin/bash
